package com.company.servicehub.repository;

import com.company.servicehub.model.Company;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import javax.persistence.EntityManager;
import java.util.List;

@Repository
public class CompanyRepository implements CompanyDao{
	
	@Autowired
	EntityManager em;

//  renamed this method to getCompany()
//	public Company findById(Long id){
//		return em.find(Company.class, id);
//	}

	@Override
	public Company getCompany(Long id) {
		return em.find(Company.class, id);
	}

	@Override
	public List<Company> getAllCompany() {
		List<Company> compList = em.createQuery("SELECT c from Company c").getResultList();
		return compList;
	}

	@Override
	@Transactional
	public Company addCompany(Company company) {
		/* Since the id is autogenerated as defined in java object model,
		 *  the object sent must not contain the id. i.e
		 *  {
		 *   "name": "Cool Airconditioners",
		 *   "phoneNumber": "(454)123",
		 *   "address": "250 Diamond St."
		 *   }
		 */
		em.persist(company);
		em.flush();
		return company;
	}

	@Override
	@Transactional
	public void updateCompany(Company company) {
		Company fromDb = em.find(Company.class, company.getId());
		fromDb.setName(company.getName());
		fromDb.setAddress(company.getAddress());
		fromDb.setPhoneNumber(company.getPhoneNumber());
		em.merge(fromDb);

	}

	@Override
	public void deleteCompany(Long id) {

	}

}
